[2024-03-17T02:17:44.667+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_to_s3.brdev scheduled__2024-03-16T00:00:00+00:00 [queued]>
[2024-03-17T02:17:44.672+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_to_s3.brdev scheduled__2024-03-16T00:00:00+00:00 [queued]>
[2024-03-17T02:17:44.672+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-17T02:17:44.681+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): brdev> on 2024-03-16 00:00:00+00:00
[2024-03-17T02:17:44.687+0000] {standard_task_runner.py:60} INFO - Started process 108 to run task
[2024-03-17T02:17:44.688+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'reddit_to_s3', 'brdev', 'scheduled__2024-03-16T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/ingest.py', '--cfg-path', '/tmp/tmpa2v3kj2d']
[2024-03-17T02:17:44.689+0000] {standard_task_runner.py:88} INFO - Job 56: Subtask brdev
[2024-03-17T02:17:44.718+0000] {task_command.py:423} INFO - Running <TaskInstance: reddit_to_s3.brdev scheduled__2024-03-16T00:00:00+00:00 [running]> on host ee31986955d4
[2024-03-17T02:17:44.769+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='reddit_to_s3' AIRFLOW_CTX_TASK_ID='brdev' AIRFLOW_CTX_EXECUTION_DATE='2024-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-16T00:00:00+00:00'
[2024-03-17T02:17:49.132+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest.py", line 30, in task_wrapper
    to_s3_bucket(file_path)
NameError: name 'to_s3_bucket' is not defined
[2024-03-17T02:17:49.138+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=reddit_to_s3, task_id=brdev, execution_date=20240316T000000, start_date=20240317T021744, end_date=20240317T021749
[2024-03-17T02:17:49.148+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 56 for task brdev (name 'to_s3_bucket' is not defined; 108)
[2024-03-17T02:17:49.192+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-17T02:17:49.204+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
